language: node_js

node_js:
  - "8"

sudo: required

services:
  - docker

after_deploy:
  - echo "done deploying"


deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: "$SECRETACCESSKEY"
  region: "ca-central-1"
  app: "elastic-beanstalk-tutorial"
  env: "elastic-beanstalk-tutorial-dev"
  bucket_name: "elastic-beanstalk-tutorial-dev.ca-central-1" # this is the URL
  on:
    branch: master
